name: Deploy GitHub Pages

on:
  push:
    branches: [ main ] # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # This is important for submodules
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build
        run: |
          # Add your build commands here if needed
          # For example: npm install && npm run build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # or your build output directory
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
